import scraperwiki
import string
import urllib2
# Blank Python
scraperwiki.sqlite.execute("drop table bbb")
scraperwiki.sqlite.execute("create table bbb ('data','url')")
#http://www.commonfloor.com/builders
mylist=[]
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=1&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=2&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=3&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=4&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=5&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=6&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=7&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=8&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=9&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=10&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=11&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=12&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=13&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=14&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=15&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=16&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=17&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=18&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=19&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=20&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=21&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=22&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=23&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=24&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=25&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=26&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=27&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=28&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=29&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=30&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=31&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=32&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=33&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=34&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=35&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=36&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=37&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=38&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=39&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=40&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=41&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=42&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=43&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=44&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=45&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=46&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=47&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=48&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=49&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=50&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=51&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=52&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=53&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=54&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=55&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=56&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=57&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=58&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=59&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=60&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=61&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=62&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=63&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=64&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=65&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=66&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=67&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=68&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=69&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=70&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=71&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=72&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=73&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=74&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=75&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=76&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=77&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=78&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=79&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=80&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=81&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=82&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=83&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=84&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=85&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=86&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=87&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=88&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=89&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=90&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=91&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=92&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=93&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=94&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=95&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=96&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=97&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=98&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=99&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=100&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=101&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=102&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=103&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=104&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=105&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=106&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=107&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=108&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=109&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=110&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=111&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=112&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=113&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=114&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=115&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=116&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=117&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=118&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=119&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=120&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=121&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=122&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=123&types_of_verbs=regular_verbs")
mylist.append("http://www.tamildiction.org/verb_dictionary/?list=124&types_of_verbs=regular_verbs")


for index in range(len(mylist)):
        try:
            data=""
            html = scraperwiki.scrape(mylist[index])
            a=html.find("Present Tense")
            n1=html.find("</div>",a)
            data=html[a:n1].strip()
            url=mylist[index]
            scraperwiki.sqlite.execute("insert into bbb values (?,?)",(data,url))
            scraperwiki.sqlite.commit()
        except urllib2.HTTPError, err:
            print err
            if err.getcode() == 404:
                continue #not a problem.  move on to next date.
